import type { Metadata } from 'next';
import './globals.css';
import { madeTommyFamily } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${madeTommyFamily.variable} antialiased`}>
        <div className='flex h-screen flex-col px-10'>
          <div className='border-foreground h-full w-full border-5'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
