import type { Metadata } from 'next';
import './globals.css';
import { madeTommyFamily } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${madeTommyFamily.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
